### ISSUE TITLE
yosys read error

### ISSUE THREAD

**Issue by archy-embedinn** [raulbehl/100DaysOfRTL#2]
Thanks for the 100 days rtl step by step guidance realy appreciate your time.

I am getting error with -gno-shared-loop-index 
also Yosys is not working with read command
i have to changed it to read_verilog, may be yosys version difference with me

**Comment by raulbehl** [comment]
Unfortunately, I had to update the `yosys` version again (to get it working with SV). I now use the version `Yosys 0.16+65 (git sha1 52d8dde, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os)` along with the `UHDM` plugin for SV support.

**Comment by raulbehl** [comment]
Marking this as closed.
