### ISSUE TITLE
Making #100DaysofRTL into challenges by adding specification in each day's readme 😄

### ISSUE THREAD

**Issue by JayKaku** [raulbehl/100DaysOfRTL#6]
If you like we could make it into challenges where each day folder would come with following

- we could have a `starter template` additional for those who wish to take the challenge (since we'll already be having tb for test)
- day specific readme with a `specification` of the module
- additional reading (prolly a link from [chipverify](https://www.chipverify.com/))

That'll be helpful for beginners mostly and people looking to revise on RTL

**Comment by raulbehl** [comment]
That is a great idea @JayKaku. But like @heyshakya said, I might be able to take out time to add the specifications for every problem and would really appreciate any help I could get. Would be happy to have you come up with the specifications.

**Comment by JayKaku** [comment]
Sure @raulbehl just lemme know if you have anything in mind with regard to the flow

**Comment by InputBlackBoxOutput** [comment]
@JayKaku Looking forward to it :-)

**Comment by raulbehl** [comment]
@JayKaku I've added a [README](https://github.com/raulbehl/100DaysOfRTL/blob/main/day1/README.md) file for day 1. Perhaps we could use that as a template and get started on adding it for other days?

**Comment by raulbehl** [comment]
I've already started adding READMEs to various problems done over the course of the challenge. Plus my RTL Design course at [QuickSilicon](https://quicksilicon.in) has bunch of problems to cover these concepts in depth with video solutions providing micro-architectural overview and line-by-line RTL walkthrough. 

Marking this as closed.
